/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carPoolingSol from "./car_pooling.sol";
export type { carPoolingSol };
import type * as contractTemplateSol from "./contract_template.sol";
export type { contractTemplateSol };
export * as factories from "./factories";
export type { CarPooling } from "./car_pooling.sol/CarPooling";
export { CarPooling__factory } from "./factories/car_pooling.sol/CarPooling__factory";
export type { CarPoolingCoordination } from "./car_pooling.sol/CarPoolingCoordination";
export { CarPoolingCoordination__factory } from "./factories/car_pooling.sol/CarPoolingCoordination__factory";
